defaults: &defaults
  adapter: postgresql
  encoding: unicode

development:
  <<: *defaults
  database: pubannotation
  pool: 5

test:
  <<: *defaults
  database: test_database

production:
  <<: *defaults
  database: pubannotation
  pool: 5
